[package]
name = "type-wiz"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
chrono = { version = "0.4.42", features = ["serde"] }
crossterm = "0.29.0"
dialoguer = "0.12.0"
ratatui = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
