name: Build and Release Installer

on:
  push:
    tags:
      - 'v*'   # タグを打ったらリリース

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Rust app
        run: cargo build --release

      - name: Get version from tag
        id: get_version
        shell: bash
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
        with:
          path: 'installer_setup.iss'
          options: /DMyAppVersion=${{ env.VERSION }}

      - name: Prepare Release Files
        shell: bash
        run: |
          cp target/release/typewiz.exe ./typewiz.exe
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            typewiz.exe
            typewiz_*_installer.exe
